---

- name: Ensure jdk package installed
  yum:
    name: '{{ packages }}'
    state: present
    update_cache: true
  vars:
    packages:
      - java-1.8.0-openjdk
- command: java -version
  register: java_version
- debug:
    msg: "Installed java X version: '{{ java_version.stderr }}'"