---

- name: Ensure Postgresql package installed
  yum:
    name: '{{ packages }}'
    state: present
    update_cache: false
  vars:
    packages:
      - '@postgresql'
- command: sudo postgresql-setup initdb
  register: pg_init_result
- debug:
    msg: "Postgres initial result: '{{ pg_init_result.stdout }}'"
- name: Ensure Postgresql service is enabled and started
  service:
    name: postgresql
    state: started
- command: systemctl status postgresql
  register: postgresql_status
- debug:
    msg: "Service postgresql status: '{{ postgresql_status.stdout }}'"